In [3]:
pip install pyxlsb

Requirement already satisfied: pyxlsb in c:\users\supre\anaconda3\lib\site-packages (1.0.10)
Note: you may need to restart the kernel to use updated packages.

In [53]:
import pandas as pd


dfc = pd.read_excel('2007-2023-PIT-Counts-by-CoC.xlsb', sheet_name=None)

df_2007 = dfc['2007'] 
df_2008 = dfc['2008']  
df_2009 = dfc['2009']
df_2010 = dfc['2010']
df_2011 = dfc['2011'] 
df_2012 = dfc['2012']
df_2013 = dfc['2013']
df_2014 = dfc['2014']
df_2015 = dfc['2015']
df_2016 = dfc['2016']
df_2017 = dfc['2017']  
df_2018 = dfc['2018']
df_2019 = dfc['2019']
df_2020 = dfc['2020']
df_2021 = dfc['2021']
df_2022 = dfc['2022']
df_2023 = dfc['2023']

In [54]:
dfc['2015'] = dfc['2015'].drop(columns='Count Types')
dfc['2015']

,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,Overall Homeless - Non-Hispanic/Non-Latin(o)(a)(x),...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK-500,Anchorage CoC,1208.0,258.0,128.0,822.0,453.0,753.0,2.0,1136.0,...,15.0,7.0,8.0,15.0,0.0,16.0,7.0,9.0,16.0,0.0
1,AK-501,Alaska Balance of State CoC,748.0,153.0,69.0,526.0,320.0,428.0,0.0,726.0,...,3.0,1.0,2.0,3.0,0.0,5.0,2.0,3.0,5.0,0.0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",1153.0,181.0,89.0,883.0,386.0,759.0,8.0,1133.0,...,6.0,3.0,3.0,6.0,0.0,13.0,6.0,7.0,13.0,0.0
3,AL-501,Mobile City & County/Baldwin County CoC,578.0,72.0,36.0,470.0,173.0,405.0,0.0,564.0,...,3.0,0.0,3.0,3.0,0.0,6.0,0.0,6.0,6.0,0.0
4,AL-502,Florence/Northwest Alabama CoC,245.0,56.0,5.0,184.0,142.0,102.0,1.0,235.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,WV-508,West Virginia Balance of State CoC,1109.0,136.0,91.0,882.0,379.0,730.0,0.0,1079.0,...,12.0,2.0,3.0,5.0,7.0,17.0,4.0,5.0,9.0,8.0
383,WY-500,Wyoming Statewide CoC,798.0,187.0,59.0,552.0,295.0,503.0,0.0,669.0,...,12.0,4.0,7.0,11.0,1.0,20.0,5.0,14.0,19.0,1.0
384,NaN,Total,564708.0,127787.0,52973.0,383948.0,224344.0,339075.0,1289.0,452140.0,...,9775.0,5650.0,3694.0,9344.0,431.0,13242.0,7432.0,5237.0,12669.0,573.0
385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
386,a MO-604 covers territory in both Missouri and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
dfc['2023'].head()

,CoC Number,CoC Name,CoC Category,Count Types,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Age 25 to 34,Overall Homeless - Age 35 to 44,Overall Homeless - Age 45 to 54,...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK-500,Anchorage CoC,Other Largely Urban CoC,Sheltered and Unsheltered Count,1760.0,185.0,161.0,377.0,419.0,315.0,...,10.0,5.0,5.0,10.0,0.0,10.0,5.0,5.0,10.0,0.0
1,AK-501,Alaska Balance of State CoC,Largely Rural CoC,Sheltered and Unsheltered Count,854.0,176.0,66.0,124.0,190.0,144.0,...,8.0,8.0,0.0,8.0,0.0,7.0,7.0,0.0,7.0,0.0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",Largely Suburban CoC,Sheltered and Unsheltered Count,847.0,67.0,42.0,127.0,182.0,180.0,...,2.0,1.0,1.0,2.0,0.0,2.0,1.0,1.0,2.0,0.0
3,AL-501,Mobile City & County/Baldwin County CoC,Other Largely Urban CoC,Sheltered and Unsheltered Count,670.0,110.0,19.0,78.0,156.0,120.0,...,2.0,2.0,0.0,2.0,0.0,2.0,2.0,0.0,2.0,0.0
4,AL-502,Florence/Northwest Alabama CoC,Largely Rural CoC,Sheltered and Unsheltered Count,195.0,63.0,9.0,42.0,36.0,23.0,...,4.0,2.0,0.0,2.0,2.0,4.0,2.0,0.0,2.0,2.0

In [56]:
dfc['2023'].columns

Index(['CoC Number', 'CoC Name', 'CoC Category', 'Count Types',
       'Overall Homeless', 'Overall Homeless - Under 18',
       'Overall Homeless - Age 18 to 24', 'Overall Homeless - Age 25 to 34',
       'Overall Homeless - Age 35 to 44', 'Overall Homeless - Age 45 to 54',
       ...
       'Overall Homeless Parenting Youth Age 18-24',
       'Sheltered ES Homeless Parenting Youth Age 18-24',
       'Sheltered TH Homeless Parenting Youth Age 18-24',
       'Sheltered Total Homeless Parenting Youth Age 18-24',
       'Unsheltered Homeless Parenting Youth Age 18-24',
       'Overall Homeless Children of Parenting Youth',
       'Sheltered ES Homeless Children of Parenting Youth',
       'Sheltered TH Homeless Children of Parenting Youth',
       'Sheltered Total Homeless Children of Parenting Youth',
       'Unsheltered Homeless Children of Parenting Youth'],
      dtype='object', length=645)

In [57]:
import pandas as pd

# Overall Homeless
dfc['2023']['Overall Homeless - Over 24'] = dfc['2023']['Overall Homeless - Age 25 to 34'] + dfc['2023']['Overall Homeless - Age 35 to 44'] + dfc['2023']['Overall Homeless - Age 45 to 54'] + dfc['2023']['Overall Homeless - Age 55 to 64'] + dfc['2023']['Overall Homeless - Over 64']

# Sheltered ES Homeless
dfc['2023']['Sheltered ES Homeless - Over 24'] = dfc['2023']['Sheltered ES Homeless - Age 25 to 34'] + dfc['2023']['Sheltered ES Homeless - Age 35 to 44'] + dfc['2023']['Sheltered ES Homeless - Age 45 to 54'] + dfc['2023']['Sheltered ES Homeless - Age 55 to 64'] + dfc['2023']['Sheltered ES Homeless - Over 64']

# Sheltered TH Homeless   
dfc['2023']['Sheltered TH Homeless - Over 24'] = dfc['2023']['Sheltered TH Homeless - Age 25 to 34'] + dfc['2023']['Sheltered TH Homeless - Age 35 to 44'] + dfc['2023']['Sheltered TH Homeless - Age 45 to 54'] + dfc['2023']['Sheltered TH Homeless - Age 55 to 64'] + dfc['2023']['Sheltered TH Homeless - Over 64']

# Sheltered SH Homeless
dfc['2023']['Sheltered SH Homeless - Over 24'] = dfc['2023']['Sheltered SH Homeless - Age 25 to 34'] + dfc['2023']['Sheltered SH Homeless - Age 35 to 44'] + dfc['2023']['Sheltered SH Homeless - Age 45 to 54'] + dfc['2023']['Sheltered SH Homeless - Age 55 to 64'] + dfc['2023']['Sheltered SH Homeless - Over 64']

# Sheltered Total Homeless
dfc['2023']['Sheltered Total Homeless - Over 24'] = dfc['2023']['Sheltered Total Homeless - Age 25 to 34'] + dfc['2023']['Sheltered Total Homeless - Age 35 to 44'] + dfc['2023']['Sheltered Total Homeless - Age 45 to 54'] + dfc['2023']['Sheltered Total Homeless - Age 55 to 64'] + dfc['2023']['Sheltered Total Homeless - Over 64']  

# Unsheltered Homeless
dfc['2023']['Unsheltered Homeless - Over 24'] = dfc['2023']['Unsheltered Homeless - Age 25 to 34'] + dfc['2023']['Unsheltered Homeless - Age 35 to 44'] + dfc['2023']['Unsheltered Homeless - Age 45 to 54'] + dfc['2023']['Unsheltered Homeless - Age 55 to 64'] + dfc['2023']['Unsheltered Homeless - Over 64']

# Overall Homeless Individuals
dfc['2023']['Overall Homeless Individuals - Over 24'] = dfc['2023']['Overall Homeless Individuals - Age 25 to 34'] + dfc['2023']['Overall Homeless Individuals - Age 35 to 44'] + dfc['2023']['Overall Homeless Individuals - Age 45 to 54'] + dfc['2023']['Overall Homeless Individuals - Age 55 to 64'] + dfc['2023']['Overall Homeless Individuals - Over 64']

# Sheltered ES Homeless Individuals
dfc['2023']['Sheltered ES Homeless Individuals - Over 24'] = dfc['2023']['Sheltered ES Homeless Individuals - Age 25 to 34'] + dfc['2023']['Sheltered ES Homeless Individuals - Age 35 to 44'] + dfc['2023']['Sheltered ES Homeless Individuals - Age 45 to 54'] + dfc['2023']['Sheltered ES Homeless Individuals - Age 55 to 64'] + dfc['2023']['Sheltered ES Homeless Individuals - Over 64']

# Sheltered TH Homeless Individuals
dfc['2023']['Sheltered TH Homeless Individuals - Over 24'] = dfc['2023']['Sheltered TH Homeless Individuals - Age 25 to 34'] + dfc['2023']['Sheltered TH Homeless Individuals - Age 35 to 44'] + dfc['2023']['Sheltered TH Homeless Individuals - Age 45 to 54'] + dfc['2023']['Sheltered TH Homeless Individuals - Age 55 to 64'] + dfc['2023']['Sheltered TH Homeless Individuals - Over 64']

# Sheltered SH Homeless Individuals
dfc['2023']['Sheltered SH Homeless Individuals - Over 24'] = dfc['2023']['Sheltered SH Homeless Individuals - Age 25 to 34'] + dfc['2023']['Sheltered SH Homeless Individuals - Age 35 to 44'] + dfc['2023']['Sheltered SH Homeless Individuals - Age 45 to 54'] + dfc['2023']['Sheltered SH Homeless Individuals - Age 55 to 64'] + dfc['2023']['Sheltered SH Homeless Individuals - Over 64']

# Sheltered Total Homeless Individuals
dfc['2023']['Sheltered Total Homeless Individuals - Over 24'] = dfc['2023']['Sheltered Total Homeless Individuals - Age 25 to 34'] + dfc['2023']['Sheltered Total Homeless Individuals - Age 35 to 44'] + dfc['2023']['Sheltered Total Homeless Individuals - Age 45 to 54'] + dfc['2023']['Sheltered Total Homeless Individuals - Age 55 to 64'] + dfc['2023']['Sheltered Total Homeless Individuals - Over 64']

# Unsheltered Homeless Individuals
dfc['2023']['Unsheltered Homeless Individuals - Over 24'] = dfc['2023']['Unsheltered Homeless Individuals - Age 25 to 34'] + dfc['2023']['Unsheltered Homeless Individuals - Age 35 to 44'] + dfc['2023']['Unsheltered Homeless Individuals - Age 45 to 54'] + dfc['2023']['Unsheltered Homeless Individuals - Age 55 to 64'] + dfc['2023']['Unsheltered Homeless Individuals - Over 64']
  
# Overall Homeless People in Families   
dfc['2023']['Overall Homeless People in Families - Over 24'] = dfc['2023']['Overall Homeless People in Families - Age 25 to 34'] + dfc['2023']['Overall Homeless People in Families - Age 35 to 44'] + dfc['2023']['Overall Homeless People in Families - Age 45 to 54'] + dfc['2023']['Overall Homeless People in Families - Age 55 to 64'] + dfc['2023']['Overall Homeless People in Families - Over 64']

# Sheltered ES Homeless People in Families
dfc['2023']['Sheltered ES Homeless People in Families - Over 24'] = dfc['2023']['Sheltered ES Homeless People in Families - Age 25 to 34'] + dfc['2023']['Sheltered ES Homeless People in Families - Age 35 to 44'] + dfc['2023']['Sheltered ES Homeless People in Families - Age 45 to 54'] + dfc['2023']['Sheltered ES Homeless People in Families - Age 55 to 64'] + dfc['2023']['Sheltered ES Homeless People in Families - Over 64'] 

# Sheltered TH Homeless People in Families  
dfc['2023']['Sheltered TH Homeless People in Families - Over 24'] = dfc['2023']['Sheltered TH Homeless People in Families - Age 25 to 34'] + dfc['2023']['Sheltered TH Homeless People in Families - Age 35 to 44'] + dfc['2023']['Sheltered TH Homeless People in Families - Age 45 to 54'] + dfc['2023']['Sheltered TH Homeless People in Families - Age 55 to 64'] + dfc['2023']['Sheltered TH Homeless People in Families - Over 64'] 

# Sheltered Total Homeless People in Families
dfc['2023']['Sheltered Total Homeless People in Families - Over 24'] = dfc['2023']['Sheltered Total Homeless People in Families - Age 25 to 34'] + dfc['2023']['Sheltered Total Homeless People in Families - Age 35 to 44'] + dfc['2023']['Sheltered Total Homeless People in Families - Age 45 to 54'] + dfc['2023']['Sheltered Total Homeless People in Families - Age 55 to 64'] + dfc['2023']['Sheltered Total Homeless People in Families - Over 64']

# Unsheltered Homeless People in Families
dfc['2023']['Unsheltered Homeless People in Families - Over 24'] = dfc['2023']['Unsheltered Homeless People in Families - Age 25 to 34'] + dfc['2023']['Unsheltered Homeless People in Families - Age 35 to 44'] + dfc['2023']['Unsheltered Homeless People in Families - Age 45 to 54'] + dfc['2023']['Unsheltered Homeless People in Families - Age 55 to 64'] + dfc['2023']['Unsheltered Homeless People in Families - Over 64']

In [58]:
dfc['2023']

,CoC Number,CoC Name,CoC Category,Count Types,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Age 25 to 34,Overall Homeless - Age 35 to 44,Overall Homeless - Age 45 to 54,...,Sheltered ES Homeless Individuals - Over 24,Sheltered TH Homeless Individuals - Over 24,Sheltered SH Homeless Individuals - Over 24,Sheltered Total Homeless Individuals - Over 24,Unsheltered Homeless Individuals - Over 24,Overall Homeless People in Families - Over 24,Sheltered ES Homeless People in Families - Over 24,Sheltered TH Homeless People in Families - Over 24,Sheltered Total Homeless People in Families - Over 24,Unsheltered Homeless People in Families - Over 24
0,AK-500,Anchorage CoC,Other Largely Urban CoC,Sheltered and Unsheltered Count,1760.0,185.0,161.0,377.0,419.0,315.0,...,976.0,9.0,0.0,985.0,324.0,105.0,48.0,57.0,105.0,0.0
1,AK-501,Alaska Balance of State CoC,Largely Rural CoC,Sheltered and Unsheltered Count,854.0,176.0,66.0,124.0,190.0,144.0,...,330.0,59.0,0.0,389.0,131.0,92.0,60.0,32.0,92.0,0.0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",Largely Suburban CoC,Sheltered and Unsheltered Count,847.0,67.0,42.0,127.0,182.0,180.0,...,268.0,64.0,9.0,341.0,363.0,34.0,27.0,4.0,31.0,3.0
3,AL-501,Mobile City & County/Baldwin County CoC,Other Largely Urban CoC,Sheltered and Unsheltered Count,670.0,110.0,19.0,78.0,156.0,120.0,...,110.0,47.0,0.0,157.0,330.0,54.0,25.0,22.0,47.0,7.0
4,AL-502,Florence/Northwest Alabama CoC,Largely Rural CoC,Sheltered and Unsheltered Count,195.0,63.0,9.0,42.0,36.0,23.0,...,26.0,46.0,0.0,72.0,27.0,24.0,11.0,12.0,23.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,WY-500,Wyoming Statewide CoC,Largely Rural CoC,Sheltered and Unsheltered Count,532.0,37.0,62.0,73.0,116.0,126.0,...,278.0,94.0,0.0,372.0,52.0,9.0,8.0,0.0,8.0,1.0
385,NaN,Total,NaN,NaN,653104.0,111620.0,47436.0,111002.0,119297.0,97289.0,...,172182.0,31169.0,1998.0,205349.0,187059.0,62887.0,48787.0,8624.0,57411.0,5476.0
386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
387,a MO-604 covers territory in both Missouri and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
388,* File does not contain the imputed ages for p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
# List of DataFrame names for the years 2015 to 2023
dfcys = [ "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023"]

# Extract the columns of 2015
dfc_2015_columns = dfc['2015'].columns

# Create modified datasets for the specified years with matched columns from 2007
dfc1 = {}

for year in dfcys:
    df = dfc[year].copy()  # Create a copy to avoid modifying in-place
    matched_columns = [col for col in df.columns if col in dfc_2015_columns]
    df = df[matched_columns]
    dfc1[year] = df  # Store the modified DataFrame in the dictionary

# Now, modified_datasets contains the modified versions of 2010 to 2022
# Access them using modified_datasets["2010"], modified_datasets["2011"], etc.

In [60]:
dfc1["2015"]

,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,Overall Homeless - Non-Hispanic/Non-Latin(o)(a)(x),...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK-500,Anchorage CoC,1208.0,258.0,128.0,822.0,453.0,753.0,2.0,1136.0,...,15.0,7.0,8.0,15.0,0.0,16.0,7.0,9.0,16.0,0.0
1,AK-501,Alaska Balance of State CoC,748.0,153.0,69.0,526.0,320.0,428.0,0.0,726.0,...,3.0,1.0,2.0,3.0,0.0,5.0,2.0,3.0,5.0,0.0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",1153.0,181.0,89.0,883.0,386.0,759.0,8.0,1133.0,...,6.0,3.0,3.0,6.0,0.0,13.0,6.0,7.0,13.0,0.0
3,AL-501,Mobile City & County/Baldwin County CoC,578.0,72.0,36.0,470.0,173.0,405.0,0.0,564.0,...,3.0,0.0,3.0,3.0,0.0,6.0,0.0,6.0,6.0,0.0
4,AL-502,Florence/Northwest Alabama CoC,245.0,56.0,5.0,184.0,142.0,102.0,1.0,235.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,WV-508,West Virginia Balance of State CoC,1109.0,136.0,91.0,882.0,379.0,730.0,0.0,1079.0,...,12.0,2.0,3.0,5.0,7.0,17.0,4.0,5.0,9.0,8.0
383,WY-500,Wyoming Statewide CoC,798.0,187.0,59.0,552.0,295.0,503.0,0.0,669.0,...,12.0,4.0,7.0,11.0,1.0,20.0,5.0,14.0,19.0,1.0
384,NaN,Total,564708.0,127787.0,52973.0,383948.0,224344.0,339075.0,1289.0,452140.0,...,9775.0,5650.0,3694.0,9344.0,431.0,13242.0,7432.0,5237.0,12669.0,573.0
385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
386,a MO-604 covers territory in both Missouri and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
dfc1["2016"]

,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,Overall Homeless - Non-Hispanic/Non-Latin(o)(a)(x),...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK-500,Anchorage CoC,1105.0,124.0,100.0,881.0,433.0,670.0,2.0,1024.0,...,6.0,1.0,5.0,6.0,0.0,6.0,1.0,5.0,6.0,0.0
1,AK-501,Alaska Balance of State CoC,835.0,150.0,73.0,612.0,375.0,457.0,3.0,773.0,...,3.0,1.0,2.0,3.0,0.0,4.0,1.0,3.0,4.0,0.0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",1228.0,192.0,119.0,917.0,465.0,757.0,6.0,1211.0,...,7.0,3.0,4.0,7.0,0.0,19.0,6.0,13.0,19.0,0.0
3,AL-501,Mobile City & County/Baldwin County CoC,623.0,93.0,30.0,500.0,215.0,406.0,2.0,605.0,...,7.0,6.0,0.0,6.0,1.0,9.0,8.0,0.0,8.0,1.0
4,AL-502,Florence/Northwest Alabama CoC,337.0,76.0,17.0,244.0,220.0,117.0,0.0,330.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,WV-508,West Virginia Balance of State CoC,748.0,112.0,55.0,581.0,264.0,484.0,0.0,735.0,...,9.0,9.0,0.0,9.0,0.0,17.0,17.0,0.0,17.0,0.0
382,WY-500,Wyoming Statewide CoC,857.0,195.0,61.0,601.0,338.0,518.0,1.0,736.0,...,15.0,8.0,4.0,12.0,3.0,17.0,8.0,6.0,14.0,3.0
383,NaN,Total,549928.0,120819.0,50001.0,379108.0,217268.0,330890.0,1770.0,428629.0,...,9800.0,5583.0,3699.0,9282.0,518.0,13318.0,7399.0,5257.0,12656.0,662.0
384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
385,a MO-604 covers territory in both Missouri and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
dfc1["2017"]

,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,Overall Homeless - Non-Hispanic/Non-Latin(o)(a)(x),...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK-500,Anchorage CoC,1128.0,170.0,133.0,825.0,445.0,678.0,4.0,1051.0,...,12.0,3.0,9.0,12.0,0.0,21.0,6.0,15.0,21.0,0.0
1,AK-501,Alaska Balance of State CoC,717.0,135.0,53.0,529.0,320.0,397.0,0.0,692.0,...,10.0,7.0,3.0,10.0,0.0,18.0,14.0,4.0,18.0,0.0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",1092.0,104.0,125.0,863.0,334.0,738.0,19.0,1075.0,...,2.0,2.0,0.0,2.0,0.0,10.0,4.0,6.0,10.0,0.0
3,AL-501,Mobile City & County/Baldwin County CoC,606.0,116.0,35.0,455.0,222.0,383.0,1.0,588.0,...,12.0,3.0,9.0,12.0,0.0,18.0,6.0,12.0,18.0,0.0
4,AL-502,Florence/Northwest Alabama CoC,155.0,0.0,8.0,147.0,72.0,81.0,0.0,152.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,WV-508,West Virginia Balance of State CoC,667.0,74.0,48.0,545.0,245.0,421.0,1.0,646.0,...,4.0,4.0,0.0,4.0,0.0,6.0,6.0,0.0,6.0,0.0
384,WY-500,Wyoming Statewide CoC,873.0,129.0,59.0,685.0,300.0,570.0,3.0,767.0,...,16.0,4.0,9.0,13.0,3.0,11.0,4.0,4.0,8.0,3.0
385,NaN,Total,550996.0,114529.0,50992.0,385475.0,214975.0,333049.0,2088.0,432634.0,...,9236.0,5868.0,2908.0,8776.0,460.0,12006.0,7336.0,4097.0,11433.0,573.0
386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
387,a MO-604 covers territory in both Missouri and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
dfc1["2018"]

,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,Overall Homeless - Non-Hispanic/Non-Latin(o)(a)(x),...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK-500,Anchorage CoC,1094.0,169.0,116.0,809.0,452.0,635.0,7.0,1031.0,...,14.0,6.0,8.0,14.0,0.0,14.0,5.0,9.0,14.0,0.0
1,AK-501,Alaska Balance of State CoC,922.0,180.0,75.0,667.0,428.0,494.0,0.0,883.0,...,11.0,8.0,1.0,9.0,2.0,12.0,9.0,1.0,10.0,2.0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",901.0,129.0,25.0,747.0,307.0,593.0,1.0,884.0,...,3.0,1.0,2.0,3.0,0.0,7.0,1.0,6.0,7.0,0.0
3,AL-501,Mobile City & County/Baldwin County CoC,551.0,97.0,30.0,424.0,200.0,349.0,2.0,531.0,...,9.0,4.0,1.0,5.0,4.0,12.0,8.0,1.0,9.0,3.0
4,AL-502,Florence/Northwest Alabama CoC,256.0,65.0,1.0,190.0,138.0,117.0,0.0,240.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,WV-508,West Virginia Balance of State CoC,628.0,72.0,27.0,529.0,234.0,393.0,1.0,622.0,...,2.0,2.0,0.0,2.0,0.0,5.0,5.0,0.0,5.0,0.0
384,WY-500,Wyoming Statewide CoC,639.0,124.0,81.0,434.0,254.0,384.0,1.0,560.0,...,8.0,4.0,4.0,8.0,0.0,6.0,1.0,5.0,6.0,0.0
385,NaN,Total,552830.0,111592.0,48319.0,392919.0,216211.0,332925.0,2521.0,430354.0,...,8637.0,5851.0,2321.0,8172.0,465.0,11320.0,7680.0,3112.0,10792.0,528.0
386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
387,a MO-604 covers territory in both Missouri and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
dfc1["2019"]

,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,Overall Homeless - Non-Hispanic/Non-Latin(o)(a)(x),...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK-500,Anchorage CoC,1111.0,193.0,132.0,786.0,422.0,685.0,4.0,1047.0,...,17.0,5.0,12.0,17.0,0.0,24.0,12.0,12.0,24.0,0.0
1,AK-501,Alaska Balance of State CoC,796.0,142.0,72.0,582.0,339.0,452.0,2.0,755.0,...,3.0,1.0,2.0,3.0,0.0,3.0,1.0,2.0,3.0,0.0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",981.0,108.0,72.0,801.0,358.0,622.0,1.0,958.0,...,7.0,0.0,7.0,7.0,0.0,7.0,0.0,7.0,7.0,0.0
3,AL-501,Mobile City & County/Baldwin County CoC,505.0,110.0,18.0,377.0,216.0,289.0,0.0,491.0,...,4.0,2.0,2.0,4.0,0.0,6.0,3.0,3.0,6.0,0.0
4,AL-502,Florence/Northwest Alabama CoC,390.0,152.0,8.0,230.0,217.0,172.0,1.0,378.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,WV-508,West Virginia Balance of State CoC,797.0,85.0,50.0,662.0,307.0,490.0,0.0,774.0,...,4.0,2.0,1.0,3.0,1.0,5.0,2.0,1.0,3.0,2.0
383,WY-500,Wyoming Statewide CoC,548.0,81.0,69.0,398.0,172.0,376.0,0.0,481.0,...,4.0,2.0,2.0,4.0,0.0,4.0,2.0,2.0,4.0,0.0
384,NaN,Total,567715.0,107069.0,45629.0,415017.0,219911.0,343187.0,3255.0,443100.0,...,7505.0,5052.0,1952.0,7004.0,501.0,9779.0,6612.0,2597.0,9209.0,570.0
385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
386,a MO-604 covers territory in both Missouri and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
dfc1["2020"]

,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,Overall Homeless - Non-Hispanic/Non-Latin(o)(a)(x),...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK-500,Anchorage CoC,1058.0,150.0,129.0,779.0,419.0,636.0,2.0,996.0,...,5.0,2.0,3.0,5.0,0.0,7.0,3.0,4.0,7.0,0.0
1,AK-501,Alaska Balance of State CoC,891.0,176.0,68.0,647.0,409.0,478.0,1.0,827.0,...,8.0,8.0,0.0,8.0,0.0,9.0,9.0,0.0,9.0,0.0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",848.0,92.0,54.0,702.0,296.0,551.0,1.0,826.0,...,8.0,3.0,5.0,8.0,0.0,11.0,4.0,7.0,11.0,0.0
3,AL-501,Mobile City & County/Baldwin County CoC,631.0,107.0,24.0,500.0,244.0,385.0,2.0,623.0,...,5.0,3.0,1.0,4.0,1.0,6.0,4.0,1.0,5.0,1.0
4,AL-502,Florence/Northwest Alabama CoC,215.0,61.0,11.0,143.0,91.0,67.0,1.0,154.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,WV-508,West Virginia Balance of State CoC,724.0,63.0,63.0,598.0,284.0,440.0,0.0,708.0,...,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,2.0,0.0
384,WY-500,Wyoming Statewide CoC,612.0,143.0,92.0,377.0,268.0,344.0,0.0,536.0,...,19.0,15.0,4.0,19.0,0.0,16.0,11.0,5.0,16.0,0.0
385,NaN,Total,580466.0,106364.0,45243.0,428859.0,223578.0,352211.0,3161.0,450107.0,...,7230.0,4938.0,1769.0,6707.0,523.0,9495.0,6415.0,2325.0,8740.0,755.0
386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
387,a MO-604 covers territory in both Missouri and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
dfc1["2021"]

,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,Overall Homeless - Non-Hispanic/Non-Latin(o)(a)(x),...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK-500,Anchorage CoC,1319.0,156.0,220.0,943.0,414.0,900.0,5.0,1243.0,...,43.0,28.0,15.0,43.0,0,38.0,19.0,19.0,38.0,0
1,AK-501,Alaska Balance of State CoC,630.0,146.0,85.0,399.0,258.0,372.0,0.0,598.0,...,15.0,7.0,8.0,15.0,0,23.0,10.0,13.0,23.0,0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",875.0,70.0,39.0,766.0,242.0,627.0,6.0,851.0,...,5.0,3.0,2.0,5.0,0,5.0,3.0,2.0,5.0,0
3,AL-501,Mobile City & County/Baldwin County CoC,219.0,78.0,6.0,135.0,96.0,123.0,0.0,218.0,...,4.0,3.0,1.0,4.0,0,9.0,6.0,3.0,9.0,0
4,AL-502,Florence/Northwest Alabama CoC,183.0,0.0,2.0,181.0,85.0,97.0,0.0,48.0,...,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,WV-508,West Virginia Balance of State CoC,619.0,65.0,59.0,495.0,262.0,356.0,1.0,607.0,...,4.0,3.0,0.0,3.0,1,4.0,3.0,0.0,3.0,1
385,WY-500,Wyoming Statewide CoC,405.0,116.0,32.0,257.0,239.0,165.0,0.0,375.0,...,6.0,6.0,0.0,6.0,0,6.0,6.0,0.0,6.0,0
386,NaN,Total,380630.0,84259.0,28289.0,259107.0,155990.0,212835.0,1544.0,290184.0,...,5965.0,4136.0,1578.0,5714.0,251,7419.0,5141.0,1944.0,7085.0,334
387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
388,a MO-604 covers territory in both Missouri and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
dfc1["2022"]

,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,Overall Homeless - Non-Hispanic/Non-Latin(o)(a)(x),...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK-500,Anchorage CoC,1494.0,182.0,145.0,1167.0,571.0,914.0,8.0,1413.0,...,9.0,5.0,4.0,9.0,0.0,9.0,5.0,4.0,9.0,0.0
1,AK-501,Alaska Balance of State CoC,826.0,146.0,58.0,622.0,321.0,503.0,0.0,793.0,...,2.0,2.0,0.0,2.0,0.0,1.0,1.0,0.0,1.0,0.0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",943.0,82.0,43.0,818.0,266.0,665.0,9.0,911.0,...,4.0,0.0,4.0,4.0,0.0,5.0,0.0,5.0,5.0,0.0
3,AL-501,Mobile City & County/Baldwin County CoC,585.0,148.0,30.0,407.0,230.0,352.0,2.0,564.0,...,7.0,6.0,1.0,7.0,0.0,10.0,9.0,1.0,10.0,0.0
4,AL-502,Florence/Northwest Alabama CoC,232.0,56.0,18.0,158.0,170.0,62.0,0.0,155.0,...,10.0,2.0,8.0,10.0,0.0,10.0,2.0,8.0,10.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,WV-508,West Virginia Balance of State CoC,720.0,47.0,74.0,599.0,287.0,424.0,1.0,704.0,...,2.0,2.0,0.0,2.0,0.0,3.0,3.0,0.0,3.0,0.0
385,WY-500,Wyoming Statewide CoC,648.0,106.0,79.0,463.0,256.0,390.0,1.0,581.0,...,7.0,4.0,3.0,7.0,0.0,8.0,5.0,3.0,8.0,0.0
386,NaN,Total,582462.0,98244.0,40177.0,444041.0,222970.0,352836.0,3588.0,442220.0,...,6348.0,4431.0,1500.0,5931.0,417.0,7961.0,5541.0,1921.0,7462.0,499.0
387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
388,a MO-604 covers territory in both Missouri and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
dfc1["2023"]

,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,Overall Homeless - Non-Hispanic/Non-Latin(o)(a)(x),Overall Homeless - Hispanic/Latin(o)(a)(x),...,Sheltered ES Homeless Individuals - Over 24,Sheltered TH Homeless Individuals - Over 24,Sheltered SH Homeless Individuals - Over 24,Sheltered Total Homeless Individuals - Over 24,Unsheltered Homeless Individuals - Over 24,Overall Homeless People in Families - Over 24,Sheltered ES Homeless People in Families - Over 24,Sheltered TH Homeless People in Families - Over 24,Sheltered Total Homeless People in Families - Over 24,Unsheltered Homeless People in Families - Over 24
0,AK-500,Anchorage CoC,1760.0,185.0,161.0,570.0,1171.0,14.0,1638.0,122.0,...,976.0,9.0,0.0,985.0,324.0,105.0,48.0,57.0,105.0,0.0
1,AK-501,Alaska Balance of State CoC,854.0,176.0,66.0,421.0,429.0,2.0,717.0,137.0,...,330.0,59.0,0.0,389.0,131.0,92.0,60.0,32.0,92.0,0.0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",847.0,67.0,42.0,256.0,579.0,11.0,822.0,25.0,...,268.0,64.0,9.0,341.0,363.0,34.0,27.0,4.0,31.0,3.0
3,AL-501,Mobile City & County/Baldwin County CoC,670.0,110.0,19.0,254.0,412.0,2.0,655.0,15.0,...,110.0,47.0,0.0,157.0,330.0,54.0,25.0,22.0,47.0,7.0
4,AL-502,Florence/Northwest Alabama CoC,195.0,63.0,9.0,117.0,78.0,0.0,186.0,9.0,...,26.0,46.0,0.0,72.0,27.0,24.0,11.0,12.0,23.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,WY-500,Wyoming Statewide CoC,532.0,37.0,62.0,158.0,372.0,0.0,462.0,70.0,...,278.0,94.0,0.0,372.0,52.0,9.0,8.0,0.0,8.0,1.0
385,NaN,Total,653104.0,111620.0,47436.0,250009.0,395160.0,4087.0,473768.0,179336.0,...,172182.0,31169.0,1998.0,205349.0,187059.0,62887.0,48787.0,8624.0,57411.0,5476.0
386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
387,a MO-604 covers territory in both Missouri and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
388,* File does not contain the imputed ages for p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
# Concatenate modified datasets horizontally
merged_dfc = pd.concat(list(dfc1.values()), axis=0, keys=dfc1.keys())

# Reset index to flatten the hierarchical columns
merged_dfc.reset_index(inplace=True, level=0)

# Display the merged DataFrame
print(merged_dfc)

    level_0                                         CoC Number  \
0      2015                                             AK-500
1      2015                                             AK-501
2      2015                                             AL-500
3      2015                                             AL-501
4      2015                                             AL-502
..      ...                                                ...
384    2023                                             WY-500
385    2023                                                NaN
386    2023                                                NaN
387    2023  a MO-604 covers territory in both Missouri and...
388    2023  * File does not contain the imputed ages for p...

                                              CoC Name  Overall Homeless  \
0                                        Anchorage CoC            1208.0
1                          Alaska Balance of State CoC             748.0
2    Birmingham/Jefferson, St. Clair, Shelby Counti...            1153.0
3              Mobile City & County/Baldwin County CoC             578.0
4                       Florence/Northwest Alabama CoC             245.0
..                                                 ...               ...
384                              Wyoming Statewide CoC             532.0
385                                              Total          653104.0
386                                                NaN               NaN
387                                                NaN               NaN
388                                                NaN               NaN

     Overall Homeless - Under 18  Overall Homeless - Age 18 to 24  \
0                          258.0                            128.0
1                          153.0                             69.0
2                          181.0                             89.0
3                           72.0                             36.0
4                           56.0                              5.0
..                           ...                              ...
384                         37.0                             62.0
385                     111620.0                          47436.0
386                          NaN                              NaN
387                          NaN                              NaN
388                          NaN                              NaN

     Overall Homeless - Over 24  Overall Homeless - Female  \
0                         822.0                      453.0
1                         526.0                      320.0
2                         883.0                      386.0
3                         470.0                      173.0
4                         184.0                      142.0
..                          ...                        ...
384                       433.0                      158.0
385                    455295.0                   250009.0
386                         NaN                        NaN
387                         NaN                        NaN
388                         NaN                        NaN

     Overall Homeless - Male  Overall Homeless - Transgender  ...  \
0                      753.0                             2.0  ...
1                      428.0                             0.0  ...
2                      759.0                             8.0  ...
3                      405.0                             0.0  ...
4                      102.0                             1.0  ...
..                       ...                             ...  ...
384                    372.0                             0.0  ...
385                 395160.0                          4087.0  ...
386                      NaN                             NaN  ...
387                      NaN                             NaN  ...
388                      NaN                             NaN  ...

     Overall Homeless Parenting Youth Age 18-24  \
0                                          15.0
1                                           3.0
2                                           6.0
3                                           3.0
4                                           0.0
..                                          ...
384                                         3.0
385                                      7130.0
386                                         NaN
387                                         NaN
388                                         NaN

     Sheltered ES Homeless Parenting Youth Age 18-24  \
0                                                7.0
1                                                1.0
2                                                3.0
3                                                0.0
4                                                0.0
..                                               ...
384                                              2.0
385                                           4954.0
386                                              NaN
387                                              NaN
388                                              NaN

     Sheltered TH Homeless Parenting Youth Age 18-24  \
0                                                8.0
1                                                2.0
2                                                3.0
3                                                3.0
4                                                0.0
..                                               ...
384                                              1.0
385                                           1558.0
386                                              NaN
387                                              NaN
388                                              NaN

     Sheltered Total Homeless Parenting Youth Age 18-24  \
0                                                 15.0
1                                                  3.0
2                                                  6.0
3                                                  3.0
4                                                  0.0
..                                                 ...
384                                                3.0
385                                             6512.0
386                                                NaN
387                                                NaN
388                                                NaN

     Unsheltered Homeless Parenting Youth Age 18-24  \
0                                               0.0
1                                               0.0
2                                               0.0
3                                               0.0
4                                               0.0
..                                              ...
384                                             0.0
385                                           618.0
386                                             NaN
387                                             NaN
388                                             NaN

     Overall Homeless Children of Parenting Youth  \
0                                            16.0
1                                             5.0
2                                            13.0
3                                             6.0
4                                             0.0
..                                            ...
384                                           4.0
385                                        8469.0
386                                           NaN
387                                           NaN
388                                           NaN

     Sheltered ES Homeless Children of Parenting Youth  \
0                                                  7.0
1                                                  2.0
2                                                  6.0
3                                                  0.0
4                                                  0.0
..                                                 ...
384                                                3.0
385                                             5909.0
386                                                NaN
387                                                NaN
388                                                NaN

     Sheltered TH Homeless Children of Parenting Youth  \
0                                                  9.0
1                                                  3.0
2                                                  7.0
3                                                  6.0
4                                                  0.0
..                                                 ...
384                                                1.0
385                                             1956.0
386                                                NaN
387                                                NaN
388                                                NaN

     Sheltered Total Homeless Children of Parenting Youth  \
0                                                 16.0
1                                                  5.0
2                                                 13.0
3                                                  6.0
4                                                  0.0
..                                                 ...
384                                                4.0
385                                             7865.0
386                                                NaN
387                                                NaN
388                                                NaN

     Unsheltered Homeless Children of Parenting Youth
0                                                 0.0
1                                                 0.0
2                                                 0.0
3                                                 0.0
4                                                 0.0
..                                                ...
384                                               0.0
385                                             604.0
386                                               NaN
387                                               NaN
388                                               NaN

[3491 rows x 385 columns]

C:\Users\supre\AppData\Local\Temp\ipykernel_25756\1897396754.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged_dfc.reset_index(inplace=True, level=0)

In [70]:
merged_dfc.head()

,level_0,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,2015,AK-500,Anchorage CoC,1208.0,258.0,128.0,822.0,453.0,753.0,2.0,...,15.0,7.0,8.0,15.0,0.0,16.0,7.0,9.0,16.0,0.0
1,2015,AK-501,Alaska Balance of State CoC,748.0,153.0,69.0,526.0,320.0,428.0,0.0,...,3.0,1.0,2.0,3.0,0.0,5.0,2.0,3.0,5.0,0.0
2,2015,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",1153.0,181.0,89.0,883.0,386.0,759.0,8.0,...,6.0,3.0,3.0,6.0,0.0,13.0,6.0,7.0,13.0,0.0
3,2015,AL-501,Mobile City & County/Baldwin County CoC,578.0,72.0,36.0,470.0,173.0,405.0,0.0,...,3.0,0.0,3.0,3.0,0.0,6.0,0.0,6.0,6.0,0.0
4,2015,AL-502,Florence/Northwest Alabama CoC,245.0,56.0,5.0,184.0,142.0,102.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [71]:
merged_dfc.rename(columns={"level_0": "Year"}, inplace=True)

In [72]:
merged_dfc.tail()

,Year,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
384,2023,WY-500,Wyoming Statewide CoC,532.0,37.0,62.0,433.0,158.0,372.0,0.0,...,3.0,2.0,1.0,3.0,0.0,4.0,3.0,1.0,4.0,0.0
385,2023,NaN,Total,653104.0,111620.0,47436.0,455295.0,250009.0,395160.0,4087.0,...,7130.0,4954.0,1558.0,6512.0,618.0,8469.0,5909.0,1956.0,7865.0,604.0
386,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
387,2023,a MO-604 covers territory in both Missouri and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
388,2023,* File does not contain the imputed ages for p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
merged_dfc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3491 entries, 0 to 388
Columns: 385 entries, Year to Unsheltered Homeless Children of Parenting Youth
dtypes: float64(315), object(70)
memory usage: 10.3+ MB

In [74]:
merged_dfc.dtypes

Year                                                     object
CoC Number                                               object
CoC Name                                                 object
Overall Homeless                                        float64
Overall Homeless - Under 18                             float64
                                                         ...
Overall Homeless Children of Parenting Youth            float64
Sheltered ES Homeless Children of Parenting Youth       float64
Sheltered TH Homeless Children of Parenting Youth       float64
Sheltered Total Homeless Children of Parenting Youth    float64
Unsheltered Homeless Children of Parenting Youth         object
Length: 385, dtype: object

In [75]:
merged_dfc.columns

Index(['Year', 'CoC Number', 'CoC Name', 'Overall Homeless',
       'Overall Homeless - Under 18', 'Overall Homeless - Age 18 to 24',
       'Overall Homeless - Over 24', 'Overall Homeless - Female',
       'Overall Homeless - Male', 'Overall Homeless - Transgender',
       ...
       'Overall Homeless Parenting Youth Age 18-24',
       'Sheltered ES Homeless Parenting Youth Age 18-24',
       'Sheltered TH Homeless Parenting Youth Age 18-24',
       'Sheltered Total Homeless Parenting Youth Age 18-24',
       'Unsheltered Homeless Parenting Youth Age 18-24',
       'Overall Homeless Children of Parenting Youth',
       'Sheltered ES Homeless Children of Parenting Youth',
       'Sheltered TH Homeless Children of Parenting Youth',
       'Sheltered Total Homeless Children of Parenting Youth',
       'Unsheltered Homeless Children of Parenting Youth'],
      dtype='object', length=385)

In [76]:
# Converting column datatypes
merged_dfc['Year'] = merged_dfc['Year'].astype('Int64')

#to preserve the NaN values and just convert the finite values to integers, 
#we use the pd.to_numeric approach with the errors='coerce' parameter:
merged_dfc.iloc[:, 3:] = merged_dfc.iloc[:, 3:].apply(pd.to_numeric, errors='coerce').astype('Int64')

In [77]:
merged_dfc.dtypes

Year                                                     Int64
CoC Number                                              object
CoC Name                                                object
Overall Homeless                                         Int64
Overall Homeless - Under 18                              Int64
                                                         ...
Overall Homeless Children of Parenting Youth             Int64
Sheltered ES Homeless Children of Parenting Youth        Int64
Sheltered TH Homeless Children of Parenting Youth        Int64
Sheltered Total Homeless Children of Parenting Youth     Int64
Unsheltered Homeless Children of Parenting Youth         Int64
Length: 385, dtype: object

In [78]:
unique_coc_names = merged_dfc['CoC Name'].unique()
print(unique_coc_names)

['Anchorage CoC' 'Alaska Balance of State CoC'
 'Birmingham/Jefferson, St. Clair, Shelby Counties CoC'
 'Mobile City & County/Baldwin County CoC'
 'Florence/Northwest Alabama CoC' 'Huntsville/North Alabama CoC'
 'Montgomery City & County CoC' 'Gadsden/Northeast Alabama CoC'
 'Tuscaloosa City & County CoC' 'Alabama Balance of State CoC'
 'Little Rock/Central Arkansas CoC' 'Fayetteville/Northwest Arkansas CoC'
 'Arkansas  Balance of State  CoC' 'Southeast Arkansas CoC'
 'Fort Smith CoC' 'Arizona Balance of State CoC' 'Tucson/Pima County CoC'
 'Phoenix, Mesa/Maricopa County CoC'
 'San Jose/Santa Clara City & County CoC' 'San Francisco CoC'
 'Oakland, Berkeley/Alameda County CoC' 'Sacramento City & County CoC'
 'Santa Rosa, Petaluma/Sonoma County CoC'
 'Richmond/Contra Costa County CoC'
 'Salinas/Monterey, San Benito Counties CoC' 'Marin County CoC'
 'Watsonville/Santa Cruz City & County CoC' 'Mendocino County CoC'
 'Turlock, Modesto/Stanislaus County CoC'
 'Stockton/San Joaquin County CoC' 'Daly/San Mateo County CoC'
 'Visalia/Kings, Tulare Counties CoC'
 'Fresno City & County/Madera County CoC'
 'Roseville, Rocklin/Placer County CoC'
 'Redding/Shasta, Siskiyou, Lassen, Plumas, Del Norte, Modoc, Sierra Counties CoC'
 'Napa City & County CoC' 'Vallejo/Solano County CoC'
 'Chico, Paradise/Butte County CoC' 'Merced City & County CoC'
 'Davis, Woodland/Yolo County CoC' 'Humboldt County CoC'
 'Colusa, Glenn, Trinity Counties CoC'
 'Yuba City & County/Sutter County CoC' 'El Dorado County CoC'
 'Amador, Calaveras, Mariposa, Tuolumne Counties CoC' 'Tehama County CoC'
 'Lake County CoC' 'Alpine, Inyo, Mono Counties CoC'
 'Los Angeles City & County CoC' 'San Diego City and County CoC'
 'Santa Ana, Anaheim/Orange County CoC'
 'Santa Maria/Santa Barbara County CoC' 'Bakersfield/Kern County CoC'
 'Long Beach CoC' 'Pasadena CoC' 'Riverside City & County CoC'
 'San Bernardino City & County CoC'
 'Oxnard, San Buenaventura/Ventura County CoC' 'Glendale CoC'
 'Imperial County CoC' 'San Luis Obispo County CoC'
 'Colorado Balance of State CoC' 'Metropolitan Denver CoC'
 'Colorado Springs/El Paso County CoC'
 'Bridgeport, Stamford, Norwalk, Danbury/Fairfield County CoC'
 'Connecticut Balance of State CoC' 'District of Columbia CoC'
 'Delaware Statewide CoC'
 'Sarasota, Bradenton/Manatee, Sarasota Counties CoC'
 'Tampa/Hillsborough County CoC'
 'St. Petersburg, Clearwater, Largo/Pinellas County CoC'
 'Lakeland, Winterhaven/Polk County CoC'
 'Deltona, Daytona Beach/Volusia, Flagler Counties CoC'
 'Fort Walton Beach/Okaloosa, Walton Counties CoC'
 'Tallahassee/Leon County CoC'
 'Orlando/Orange, Osceola, Seminole Counties CoC'
 'Gainesville/Alachua, Putnam Counties CoC'
 'Fort Pierce/St. Lucie, Indian River, Martin Counties CoC'
 'Jacksonville-Duval, Clay Counties CoC'
 'Pensacola/Escambia, Santa Rosa Counties CoC' 'St. Johns County CoC'
 'Palm Bay, Melbourne/Brevard County CoC' 'Ocala/Marion County CoC'
 'Panama City/Bay, Jackson Counties CoC'
 'Hendry, Hardee, Highlands Counties CoC'
 'Columbia, Hamilton, Lafayette, Suwannee Counties CoC' 'Pasco County CoC'
 'Citrus, Hernando, Lake, Sumter Counties CoC' 'Miami-Dade County CoC'
 'Ft Lauderdale/Broward County CoC' 'Punta Gorda/Charlotte County CoC'
 'Ft Myers, Cape Coral/Lee County CoC' 'Monroe County CoC'
 'West Palm Beach/Palm Beach County CoC' 'Naples/Collier County CoC'
 'Atlanta CoC' 'Georgia Balance of State CoC' 'Fulton County CoC'
 'Athens-Clarke County CoC' 'Augusta-Richmond County CoC'
 'Columbus-Muscogee CoC' 'Marietta/Cobb County CoC'
 'Savannah/Chatham County CoC' 'DeKalb County CoC' 'Guam CoC'
 'Hawaii Balance of State CoC' 'Honolulu City and County CoC'
 'Sioux City/Dakota, Woodbury Counties CoC' 'Iowa Balance of State CoC'
 'Des Moines/Polk County CoC' 'Boise/Ada County CoC'
 'Idaho Balance of State CoC' 'McHenry County CoC'
 'Rockford/DeKalb, Winnebago, Boone Counties CoC'
 'Waukegan, North Chicago/Lake County CoC'
 'Champaign, Urbana, Rantoul/Champaign County CoC' 'Madison County CoC'
 'Joliet, Bolingbrook/Will County CoC'
 'Peoria, Pekin/Fulton, Tazewell, Peoria, Woodford Counties CoC'
 'East St. Louis, Belleville/St. Clair County CoC' 'Chicago CoC'
 'Cook County CoC' 'Bloomington/Central Illinois CoC'
 'Springfield/Sangamon County CoC' 'DuPage County CoC'
 'South Central Illinois CoC' 'Decatur/Macon County CoC'
 'Aurora, Elgin/Kane County CoC'
 'Rock Island, Moline/Northwestern Illinois CoC'
 'West Central Illinois CoC' 'Southern Illinois CoC'
 'Indiana Balance of State CoC' 'Indianapolis CoC'
 'Wichita/Sedgwick County CoC' 'Topeka/Shawnee County CoC'
 'Overland Park, Shawnee/Johnson County CoC' 'Kansas Balance of State CoC'
 'Kentucky Balance of State CoC' 'Louisville-Jefferson County CoC'
 'Lexington-Fayette County CoC' 'Lafayette/Acadiana CoC'
 'Shreveport, Bossier/Northwest Louisiana CoC'
 'New Orleans/Jefferson Parish CoC' 'Monroe/Northeast Louisiana CoC'
 'Slidell/Southeast Louisiana CoC' 'Alexandria/Central Louisiana CoC'
 'Louisiana Balance of State CoC' 'Boston CoC' 'Lynn CoC'
 'Cape Cod Islands CoC' 'Springfield/Hampden County CoC' 'New Bedford CoC'
 'Worcester City & County CoC'
 'Pittsfield/Berkshire, Franklin, Hampshire Counties CoC' 'Cambridge CoC'
 'Quincy, Brockton, Weymouth, Plymouth City and County CoC'
 'Fall River CoC' 'Massachusetts Balance of State CoC'
 'Attleboro, Taunton/Bristol County CoC' 'Baltimore CoC'
 'Annapolis/Anne Arundel County CoC' 'Howard County CoC'
 'Baltimore County CoC' 'Carroll County CoC' 'Mid-Shore Regional CoC'
 'Wicomico, Somerset, Worcester Counties CoC'
 'Maryland Balance of State CoC' "Prince George's County CoC"
 'Montgomery County CoC' 'Maine Statewide CoC'
 'Michigan Balance of State CoC' 'Detroit CoC'
 'Dearborn, Dearborn Heights, Westland/Wayne County CoC'
 'St. Clair Shores, Warren/Macomb County CoC'
 'Pontiac, Royal Oak/Oakland County CoC' 'Flint/Genesee County CoC'
 'Grand Rapids, Wyoming/Kent County CoC'
 'Portage, Kalamazoo City & County CoC'
 'Lansing, East Lansing/Ingham County CoC' 'Washtenaw County CoC'
 'Saginaw City & County CoC' 'Lenawee County CoC'
 'Grand Traverse, Antrim, Leelanau Counties CoC'
 'Battle Creek/Calhoun County CoC' 'Monroe City & County CoC'
 'Norton Shores, Muskegon City & County CoC' 'Jackson City & County CoC'
 'Livingston County CoC' 'Holland/Ottawa County CoC' 'Eaton County CoC'
 'Minneapolis/Hennepin County CoC' 'Saint Paul/Ramsey County CoC'
 'Rochester/Southeast Minnesota CoC'
 'Dakota, Anoka, Washington, Scott, Carver Counties'
 'Northeast Minnesota CoC' 'St. Cloud/Central Minnesota CoC'
 'Northwest Minnesota CoC' 'Moorhead/West Central Minnesota CoC'
 'Duluth/St.Louis County CoC' 'Southwest Minnesota CoC'
 'St. Louis County CoC' 'St.Louis City CoC'
 'St. Charles City & County, Lincoln, Warren Counties CoC'
 'Springfield/Greene, Christian, Webster Counties CoC'
 'Joplin/Jasper, Newton Counties CoC'
 'St. Joseph/Andrew, Buchanan, DeKalb Counties CoC'
 'Kansas City, Independence, Lee’s Summit/Jackson, Wyandotte Counties, MO & KS'
 'Missouri Balance of State CoC' 'Jackson/Rankin, Madison Counties CoC'
 'Mississippi Balance of State CoC' 'Gulf Port/Gulf Coast Regional CoC'
 'Montana Statewide CoC' 'Winston-Salem/Forsyth County CoC'
 'Asheville/Buncombe County CoC' 'Durham City & County CoC'
 'North Carolina Balance of State CoC' 'Greensboro, High Point CoC'
 'Charlotte/Mecklenberg CoC'
 'Wilmington/Brunswick, New Hanover, Pender Counties CoC'
 'Raleigh/Wake County CoC'
 'Gastonia/Cleveland, Gaston, Lincoln Counties CoC'
 'Fayetteville/Cumberland County CoC' 'Chapel Hill/Orange County CoC'
 'Northwest North Carolina CoC' 'North Dakota Statewide CoC'
 'Nebraska Balance of State CoC' 'Omaha, Council Bluffs CoC' 'Lincoln CoC'
 'New Hampshire Balance of State CoC' 'Manchester CoC'
 'Nashua/Hillsborough County CoC' 'Atlantic City & County CoC'
 'Bergen County CoC' 'Burlington County CoC'
 'Camden City & County/Gloucester, Cape May, Cumberland Counties CoC'
 'Newark/Essex County CoC' 'Jersey City, Bayonne/Hudson County CoC'
 'New Brunswick/Middlesex County CoC' 'Monmouth County CoC'
 'Morris County CoC' 'Lakewood Township/Ocean County CoC'
 'Paterson/Passaic County CoC' 'Salem County CoC' 'Somerset County CoC'
 'Trenton/Mercer County CoC' 'Elizabeth/Union County CoC'
 'Warren, Sussex, Hunterdon Counties CoC' 'Albuquerque CoC'
 'New Mexico Balance of State CoC' 'Las Vegas/Clark County CoC'
 'Reno, Sparks/Washoe County CoC' 'Nevada Balance of State CoC'
 'Rochester, Irondequoit, Greece/Monroe County CoC'
 'Elmira/Steuben, Allegany, Livingston, Chemung, Schuyler Counties CoC'
 'Albany City & County CoC' 'Cattaragus County CoC'
 'Syracuse, Auburn/Onondaga, Oswego, Cayuga Counties CoC'
 'Schenectady City & County CoC'
 'Buffalo, Niagara Falls/Erie, Niagara, Orleans, Genesee, Wyoming Counties CoC'
 'Ithaca/Tompkins County CoC'
 'Binghamton, Union Town/Broome, Otsego, Chenango, Delaware, Cortland, Tioga Count'
 'Troy/Rensselaer County CoC' 'Wayne, Ontario, Seneca, Yates Counties CoC'
 'Jamestown, Dunkirk/Chautauqua County CoC' 'Clinton County CoC'
 'Utica, Rome/Oneida, Madison Counties CoC'
 'Columbia, Greene Counties CoC' 'Franklin, Essex Counties CoC'
 'Jefferson, Lewis, St. Lawrence Counties CoC'
 'Glens Falls, Saratoga Springs/Saratoga, Washington, Warren, Hamilton Counties Co'
 'New York City CoC' 'Poughkeepsie/Dutchess County CoC'
 'Newburgh, Middletown/Orange County CoC' 'Nassau, Suffolk Counties CoC'
 'Yonkers, Mount Vernon/Westchester County CoC' 'Rockland County CoC'
 'Sullivan County CoC' 'Kingston/Ulster County CoC'
 'Cincinnati/Hamilton County CoC' 'Toledo/Lucas County CoC'
 'Cleveland/Cuyahoga County CoC' 'Columbus/Franklin County CoC'
 'Youngstown/Mahoning County CoC'
 'Dayton, Kettering/Montgomery County CoC'
 'Akron, Barberton/Summit County CoC' 'Ohio Balance of State CoC'
 'Canton, Massillon, Alliance/Stark County CoC'
 'North Central Oklahoma CoC' 'Tulsa City & County CoC'
 'Oklahoma City CoC' 'Oklahoma Balance of State CoC'
 'Norman/Cleveland County CoC' 'Northeast Oklahoma CoC'
 'Southwest Oklahoma Regional CoC' 'Southeastern Oklahoma Regional CoC'
 'Eugene, Springfield/Lane County CoC'
 'Portland, Gresham/Multnomah County CoC'
 'Medford, Ashland/Jackson County CoC' 'Central Oregon CoC'
 'Oregon Balance of State CoC'
 'Hillsboro, Beaverton/Washington County CoC' 'Clackamas County CoC'
 'Philadelphia CoC' 'Harrisburg/Dauphin County CoC'
 'Upper Darby, Chester, Haverford/Delaware County CoC'
 'Wilkes-Barre, Hazleton/Luzerne County CoC'
 'Lower Merion, Norristown, Abington/Montgomery County CoC'
 'Chester County CoC' 'Reading/Berks County CoC'
 'Scranton/Lackawanna County CoC' 'Eastern Pennsylvania CoC'
 'Lancaster City & County CoC' 'Bristol, Bensalem/Bucks County CoC'
 'York City & County CoC'
 'Pittsburgh, McKeesport, Penn Hills/Allegheny County CoC'
 'Western Pennsylvania CoC' 'Beaver County CoC' 'Erie City & County CoC'
 'Puerto Rico Balance of Commonwealth CoC'
 'South-Southeast Puerto Rico CoC' 'Rhode Island Statewide CoC'
 'Charleston/Low Country CoC'
 'Greenville, Anderson, Spartanburg/Upstate CoC' 'Columbia/Midlands CoC'
 'Myrtle Beach, Sumter City & County CoC' 'South Dakota Statewide CoC'
 'Chattanooga/Southeast Tennessee CoC' 'Memphis/Shelby County CoC'
 'Knoxville/Knox County CoC' 'Central Tennessee CoC'
 'Nashville-Davidson County CoC' 'Upper Cumberland CoC'
 'Jackson/West Tennessee CoC' 'Appalachian Regional CoC'
 'Murfreesboro/Rutherford County CoC'
 'Morristown/Blount, Sevier, Campbell, Cocke Counties CoC'
 'San Antonio/Bexar County CoC' 'Austin/Travis County CoC'
 'Dallas City & County, Irving CoC'
 'Fort Worth, Arlington/Tarrant County CoC' 'El Paso City & County CoC'
 'Waco/McLennan County CoC' 'Texas Balance of State CoC' 'Amarillo CoC'
 'Wichita Falls/Wise, Palo Pinto, Wichita, Archer Counties CoC'
 'Houston, Pasadena, Conroe/Harris, Ft. Bend, Montgomery, Counties CoC'
 'Bryan, College Station/Brazos Valley CoC' 'Salt Lake City & County CoC'
 'Utah Balance of State CoC' 'Provo/Mountainland CoC'
 'Richmond/Henrico, Chesterfield, Hanover Counties CoC'
 'Norfolk, Chesapeake, Suffolk/Isle of Wight, Southampton Counties CoC'
 'Roanoke City & County, Salem CoC' 'Virginia Beach CoC'
 'Charlottesville CoC' 'Newport News, Hampton/Virginia Peninsula CoC'
 'Portsmouth CoC' 'Lynchburg CoC'
 'Harrisburg, Winchester/Western Virginia CoC'
 'Fredericksburg/Spotsylvania, Stafford Counties CoC'
 'Virginia Balance of State CoC' 'Arlington County CoC'
 'Fairfax County CoC' 'Loudoun County CoC' 'Alexandria CoC'
 'Prince William County CoC' 'Virgin Islands CoC'
 'Vermont Balance of State CoC' 'Burlington/Chittenden County CoC'
 'Seattle/King County CoC' 'Washington Balance of State CoC'
 'Spokane City & County CoC' 'Tacoma, Lakewood/Pierce County CoC'
 'Everett/Snohomish County CoC' 'Vancouver/Clark County CoC'
 'Wisconsin Balance of State CoC' 'Milwaukee City & County CoC'
 'Racine City & County CoC' 'Madison/Dane County CoC'
 'Wheeling, Weirton Area CoC' 'Huntington/Cabell, Wayne Counties CoC'
 'Charleston/Kanawha, Putnam, Boone, Clay Counties CoC'
 'West Virginia Balance of State CoC' 'Wyoming Statewide CoC' 'Total' nan
 'Northern Mariana Islands CoC' 'Nevada County CoC'
 'New York Balance of State Continuum of Care'
 'Fort Collins, Greeley, Loveland/Larimer, Weld Counties CoC'
 'Salem/Marion, Polk Counties CoC']

In [79]:
len(unique_coc_names)

391

In [80]:
unique_coc_number = merged_dfc['CoC Number'].unique()
print(unique_coc_number)

['AK-500' 'AK-501' 'AL-500' 'AL-501' 'AL-502' 'AL-503' 'AL-504' 'AL-505'
 'AL-506' 'AL-507' 'AR-500' 'AR-501' 'AR-503' 'AR-505' 'AR-508' 'AZ-500'
 'AZ-501' 'AZ-502' 'CA-500' 'CA-501' 'CA-502' 'CA-503' 'CA-504' 'CA-505'
 'CA-506' 'CA-507' 'CA-508' 'CA-509' 'CA-510' 'CA-511' 'CA-512' 'CA-513'
 'CA-514' 'CA-515' 'CA-516' 'CA-517' 'CA-518' 'CA-519' 'CA-520' 'CA-521'
 'CA-522' 'CA-523' 'CA-524' 'CA-525' 'CA-526' 'CA-527' 'CA-529' 'CA-530'
 'CA-600' 'CA-601' 'CA-602' 'CA-603' 'CA-604' 'CA-606' 'CA-607' 'CA-608'
 'CA-609' 'CA-611' 'CA-612' 'CA-613' 'CA-614' 'CO-500' 'CO-503' 'CO-504'
 'CT-503' 'CT-505' 'DC-500' 'DE-500' 'FL-500' 'FL-501' 'FL-502' 'FL-503'
 'FL-504' 'FL-505' 'FL-506' 'FL-507' 'FL-508' 'FL-509' 'FL-510' 'FL-511'
 'FL-512' 'FL-513' 'FL-514' 'FL-515' 'FL-517' 'FL-518' 'FL-519' 'FL-520'
 'FL-600' 'FL-601' 'FL-602' 'FL-603' 'FL-604' 'FL-605' 'FL-606' 'GA-500'
 'GA-501' 'GA-502' 'GA-503' 'GA-504' 'GA-505' 'GA-506' 'GA-507' 'GA-508'
 'GU-500' 'HI-500' 'HI-501' 'IA-500' 'IA-501' 'IA-502' 'ID-500' 'ID-501'
 'IL-500' 'IL-501' 'IL-502' 'IL-503' 'IL-504' 'IL-506' 'IL-507' 'IL-508'
 'IL-510' 'IL-511' 'IL-512' 'IL-513' 'IL-514' 'IL-515' 'IL-516' 'IL-517'
 'IL-518' 'IL-519' 'IL-520' 'IN-502' 'IN-503' 'KS-502' 'KS-503' 'KS-505'
 'KS-507' 'KY-500' 'KY-501' 'KY-502' 'LA-500' 'LA-502' 'LA-503' 'LA-505'
 'LA-506' 'LA-507' 'LA-509' 'MA-500' 'MA-502' 'MA-503' 'MA-504' 'MA-505'
 'MA-506' 'MA-507' 'MA-509' 'MA-511' 'MA-515' 'MA-516' 'MA-519' 'MD-501'
 'MD-503' 'MD-504' 'MD-505' 'MD-506' 'MD-511' 'MD-513' 'MD-514' 'MD-600'
 'MD-601' 'ME-500' 'MI-500' 'MI-501' 'MI-502' 'MI-503' 'MI-504' 'MI-505'
 'MI-506' 'MI-507' 'MI-508' 'MI-509' 'MI-510' 'MI-511' 'MI-512' 'MI-514'
 'MI-515' 'MI-516' 'MI-517' 'MI-518' 'MI-519' 'MI-523' 'MN-500' 'MN-501'
 'MN-502' 'MN-503' 'MN-504' 'MN-505' 'MN-506' 'MN-508' 'MN-509' 'MN-511'
 'MO-500' 'MO-501' 'MO-503' 'MO-600' 'MO-602' 'MO-603' 'MO-604a' 'MO-606'
 'MS-500' 'MS-501' 'MS-503' 'MT-500' 'NC-500' 'NC-501' 'NC-502' 'NC-503'
 'NC-504' 'NC-505' 'NC-506' 'NC-507' 'NC-509' 'NC-511' 'NC-513' 'NC-516'
 'ND-500' 'NE-500' 'NE-501' 'NE-502' 'NH-500' 'NH-501' 'NH-502' 'NJ-500'
 'NJ-501' 'NJ-502' 'NJ-503' 'NJ-504' 'NJ-506' 'NJ-507' 'NJ-508' 'NJ-509'
 'NJ-510' 'NJ-511' 'NJ-512' 'NJ-513' 'NJ-514' 'NJ-515' 'NJ-516' 'NM-500'
 'NM-501' 'NV-500' 'NV-501' 'NV-502' 'NY-500' 'NY-501' 'NY-503' 'NY-504'
 'NY-505' 'NY-507' 'NY-508' 'NY-510' 'NY-511' 'NY-512' 'NY-513' 'NY-514'
 'NY-516' 'NY-518' 'NY-519' 'NY-520' 'NY-522' 'NY-523' 'NY-600' 'NY-601'
 'NY-602' 'NY-603' 'NY-604' 'NY-606' 'NY-607' 'NY-608' 'OH-500' 'OH-501'
 'OH-502' 'OH-503' 'OH-504' 'OH-505' 'OH-506' 'OH-507' 'OH-508' 'OK-500'
 'OK-501' 'OK-502' 'OK-503' 'OK-504' 'OK-505' 'OK-506' 'OK-507' 'OR-500'
 'OR-501' 'OR-502' 'OR-503' 'OR-505' 'OR-506' 'OR-507' 'PA-500' 'PA-501'
 'PA-502' 'PA-503' 'PA-504' 'PA-505' 'PA-506' 'PA-508' 'PA-509' 'PA-510'
 'PA-511' 'PA-512' 'PA-600' 'PA-601' 'PA-603' 'PA-605' 'PR-502' 'PR-503'
 'RI-500' 'SC-500' 'SC-501' 'SC-502' 'SC-503' 'SD-500' 'TN-500' 'TN-501'
 'TN-502' 'TN-503' 'TN-504' 'TN-506' 'TN-507' 'TN-509' 'TN-510' 'TN-512'
 'TX-500' 'TX-503' 'TX-600' 'TX-601' 'TX-603' 'TX-604' 'TX-607' 'TX-611'
 'TX-624' 'TX-700' 'TX-701' 'UT-500' 'UT-503' 'UT-504' 'VA-500' 'VA-501'
 'VA-502' 'VA-503' 'VA-504' 'VA-505' 'VA-507' 'VA-508' 'VA-513' 'VA-514'
 'VA-521' 'VA-600' 'VA-601' 'VA-602' 'VA-603' 'VA-604' 'VI-500' 'VT-500'
 'VT-501' 'WA-500' 'WA-501' 'WA-502' 'WA-503' 'WA-504' 'WA-508' 'WI-500'
 'WI-501' 'WI-502' 'WI-503' 'WV-500' 'WV-501' 'WV-503' 'WV-508' 'WY-500'
 nan
 "a MO-604 covers territory in both Missouri and Kansas. The record described in this file represents the CoC's total territory, the sum of the point-in-time estimates the CoC separately reported for the portions of its territory in MO and in KS. However, in the companion file, Point-in-Time Estimates by State, MO-604's data have been split up between MO and KS."
 'MP-500' 'CA-531' 'NY-525' 'CO-505' 'OR-504'
 '* File does not contain the imputed ages for people experiencing unsheltered homelessness over age 24 for the 22 CoCs that did not conduct an unsheltered count in 2023. ']

"a MO-604 covers territory in both Missouri and Kansas. The record described in this file represents the CoC's total territory, the sum of the point-in-time estimates the CoC separately reported for the portions of its territory in MO and in KS. However, in the companion file, Point-in-Time Estimates by State, MO-604's data have been split up between MO and KS."

'* File does not contain the imputed ages for people experiencing unsheltered homelessness over age 24 for the 22 CoCs that did not conduct an unsheltered count in 2023. '

In [82]:
# Filter the DataFrame to select only rows where 'CoC Number' is 'NJ-512'
filtered_rows = merged_dfc[merged_dfc['CoC Number'] == 'NJ-512']

# Calculate the average across all numeric columns except 'Year', 'CoC Number', and 'CoC Name'
average_row = filtered_rows.drop(columns=['Year', 'CoC Number', 'CoC Name']).mean().round().astype(int)

# Create a new DataFrame with the average values
new_row = pd.DataFrame(average_row).T

# Assign the specified 'Year', 'CoC Number', and 'CoC Name' to the new row
new_row['Year'] = 2016
new_row['CoC Number'] = 'NJ-512'
new_row['CoC Name'] = filtered_rows.iloc[0]['CoC Name']  # Assuming all CoC Names are the same for NJ-512

# Reorder the columns to match the original DataFrame
new_row = new_row[['Year', 'CoC Number', 'CoC Name'] + new_row.columns[:-3].tolist()]

new_row

,Year,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,2016,NJ-512,Salem County CoC,34,10,2,21,17,17,0,...,0,0,0,0,0,0,0,0,0,0

In [83]:
# Concatenate the original DataFrame with the new row
merged_dfc = pd.concat([merged_dfc, new_row], ignore_index=True)

# Filter the concatenated DataFrame to select only rows where 'CoC Number' is 'NJ-512'
rows_with_NJ_512 = merged_dfc[merged_dfc['CoC Number'] == 'NJ-512']
rows_with_NJ_512

,Year,CoC Number,CoC Name,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
242,2015,NJ-512,Salem County CoC,38,13,4,21,18,20,0,...,0,0,0,0,0,0,0,0,0,0
1016,2017,NJ-512,Salem County CoC,16,4,2,10,8,8,0,...,0,0,0,0,0,0,0,0,0,0
1404,2018,NJ-512,Salem County CoC,49,21,4,24,23,26,0,...,0,0,0,0,0,0,0,0,0,0
1793,2019,NJ-512,Salem County CoC,29,14,0,15,16,13,0,...,0,0,0,0,0,0,0,0,0,0
2180,2020,NJ-512,Salem County CoC,32,8,0,24,20,12,0,...,0,0,0,0,0,0,0,0,0,0
2569,2021,NJ-512,Salem County CoC,18,6,1,11,11,7,0,...,0,0,0,0,0,0,0,0,0,0
2958,2022,NJ-512,Salem County CoC,20,6,2,12,6,14,0,...,0,0,0,0,0,0,0,0,0,0
3346,2023,NJ-512,Salem County CoC,67,6,7,54,32,35,0,...,0,0,0,0,0,0,0,0,0,0
3491,2016,NJ-512,Salem County CoC,34,10,2,21,17,17,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
x = merged_dfc.columns
print(x)

Index(['Year', 'CoC Number', 'CoC Name', 'Overall Homeless',
       'Overall Homeless - Under 18', 'Overall Homeless - Age 18 to 24',
       'Overall Homeless - Over 24', 'Overall Homeless - Female',
       'Overall Homeless - Male', 'Overall Homeless - Transgender',
       ...
       'Overall Homeless Parenting Youth Age 18-24',
       'Sheltered ES Homeless Parenting Youth Age 18-24',
       'Sheltered TH Homeless Parenting Youth Age 18-24',
       'Sheltered Total Homeless Parenting Youth Age 18-24',
       'Unsheltered Homeless Parenting Youth Age 18-24',
       'Overall Homeless Children of Parenting Youth',
       'Sheltered ES Homeless Children of Parenting Youth',
       'Sheltered TH Homeless Children of Parenting Youth',
       'Sheltered Total Homeless Children of Parenting Youth',
       'Unsheltered Homeless Children of Parenting Youth'],
      dtype='object', length=385)

In [28]:
null_values = merged_dfc.isnull().sum()
print(null_values)

Year                                                     0
CoC Number                                              18
CoC Name                                                19
Overall Homeless                                        19
Overall Homeless - Under 18                             19
                                                        ..
Overall Homeless Children of Parenting Youth            19
Sheltered ES Homeless Children of Parenting Youth       19
Sheltered TH Homeless Children of Parenting Youth       19
Sheltered Total Homeless Children of Parenting Youth    19
Unsheltered Homeless Children of Parenting Youth        61
Length: 385, dtype: int64

In [68]:
# fill null
merged_df = merged_df.fillna('0')

In [69]:
null_values = merged_df.isnull().sum()
print(null_values)

Year                                                                         0
CoC Number                                                                   0
CoC Name                                                                     0
Overall Homeless                                                             0
Overall Homeless - Under 18                                                  0
                                                                            ..
Unsheltered Homeless Veterans - Black or African American                    0
Unsheltered Homeless Veterans - Asian                                        0
Unsheltered Homeless Veterans - American Indian or Alaska Native             0
Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander    0
Unsheltered Homeless Veterans - Multiple Races                               0
Length: 347, dtype: int64

In [70]:
print(merged_df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3116 entries, 0 to 389
Columns: 347 entries, Year to Unsheltered Homeless Veterans - Multiple Races
dtypes: Int64(345), object(2)
memory usage: 9.3+ MB
None

In [ ]:
output_file = 'merged_dfc.xlsx'
merged_dfc.to_excel(output_file, index=False)

In [71]:
merged_df.describe()

,Year,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,Overall Homeless - Non-Hispanic/Non-Latino,Overall Homeless - Hispanic/Latino,Overall Homeless - White,Overall Homeless - Black or African American,Overall Homeless - Asian,Overall Homeless - American Indian or Alaska Native,Overall Homeless - Native Hawaiian or Other Pacific Islander,Overall Homeless - Multiple Races,Sheltered ES Homeless,Sheltered ES Homeless - Under 18,Sheltered ES Homeless - Age 18 to 24,Sheltered ES Homeless - Over 24,Sheltered ES Homeless - Female,Sheltered ES Homeless - Male,Sheltered ES Homeless - Transgender,Sheltered ES Homeless - Non-Hispanic/Non-Latino,Sheltered ES Homeless - Hispanic/Latino,Sheltered ES Homeless - White,Sheltered ES Homeless - Black or African American,Sheltered ES Homeless - Asian,Sheltered ES Homeless - American Indian or Alaska Native,Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander,Sheltered ES Homeless - Multiple Races,Sheltered TH Homeless,Sheltered TH Homeless - Under 18,Sheltered TH Homeless - Age 18 to 24,Sheltered TH Homeless - Over 24,Sheltered TH Homeless - Female,Sheltered TH Homeless - Male,Sheltered TH Homeless - Transgender,Sheltered TH Homeless - Non-Hispanic/Non-Latino,Sheltered TH Homeless - Hispanic/Latino,Sheltered TH Homeless - White,Sheltered TH Homeless - Black or African American,Sheltered TH Homeless - Asian,Sheltered TH Homeless - American Indian or Alaska Native,Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander,Sheltered TH Homeless - Multiple Races,Sheltered SH Homeless,Sheltered SH Homeless - Age 18 to 24,Sheltered SH Homeless - Over 24,Sheltered SH Homeless - Female,Sheltered SH Homeless - Male,Sheltered SH Homeless - Transgender,Sheltered SH Homeless - Non-Hispanic/Non-Latino,Sheltered SH Homeless - Hispanic/Latino,Sheltered SH Homeless - White,Sheltered SH Homeless - Black or African American,Sheltered SH Homeless - Asian,Sheltered SH Homeless - American Indian or Alaska Native,Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander,Sheltered SH Homeless - Multiple Races,Sheltered Total Homeless,Sheltered Total Homeless - Under 18,Sheltered Total Homeless - Age 18 to 24,Sheltered Total Homeless - Over 24,Sheltered Total Homeless - Female,Sheltered Total Homeless - Male,Sheltered Total Homeless - Transgender,Sheltered Total Homeless - Non-Hispanic/Non-Latino,Sheltered Total Homeless - Hispanic/Latino,Sheltered Total Homeless - White,Sheltered Total Homeless - Black or African American,Sheltered Total Homeless - Asian,Sheltered Total Homeless - American Indian or Alaska Native,Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander,Sheltered Total Homeless - Multiple Races,Unsheltered Homeless,Unsheltered Homeless - Under 18,Unsheltered Homeless - Age 18 to 24,Unsheltered Homeless - Over 24,Unsheltered Homeless - Female,Unsheltered Homeless - Male,Unsheltered Homeless - Transgender,Unsheltered Homeless - Non-Hispanic/Non-Latino,Unsheltered Homeless - Hispanic/Latino,Unsheltered Homeless - White,Unsheltered Homeless - Black or African American,Unsheltered Homeless - Asian,Unsheltered Homeless - American Indian or Alaska Native,Unsheltered Homeless - Native Hawaiian or Other Pacific Islander,Unsheltered Homeless - Multiple Races,Overall Homeless Individuals,Overall Homeless Individuals - Under 18,Overall Homeless Individuals - Age 18 to 24,Overall Homeless Individuals - Over 24,Overall Homeless Individuals - Female,Overall Homeless Individuals - Male,Overall Homeless Individuals - Transgender,Overall Homeless Individuals - Non-Hispanic/Non-Latino,Overall Homeless Individuals - Hispanic/Latino,Overall Homeless Individuals - White,Overall Homeless Individuals - Black or African American,Overall Homeless Individuals - Asian,Overall Homeless Individuals - American Indian or Alaska Native,Overall Homeless Individuals - Native Hawaiian or Other Pacific Islander,Overall Homeless Individuals - Multiple Races,Sheltered ES Homeless Individuals,Sheltered ES Homeless Individuals - Under 18,Sheltered ES Homeless Individuals - Age 18 to 24,Sheltered ES Homeless Individuals - Over 24,Sheltered ES Homeless Individuals - Female,Sheltered ES Homeless Individuals - Male,Sheltered ES Homeless Individuals - Transgender,Sheltered ES Homeless Individuals - Non-Hispanic/Non-Latino,Sheltered ES Homeless Individuals - Hispanic/Latino,Sheltered ES Homeless Individuals - White,Sheltered ES Homeless Individuals - Black or African American,Sheltered ES Homeless Individuals - Asian,Sheltered ES Homeless Individuals - American Indian or Alaska Native,Sheltered ES Homeless Individuals - Native Hawaiian or Other Pacific Islander,Sheltered ES Homeless Individuals - Multiple Races,Sheltered TH Homeless Individuals,Sheltered TH Homeless Individuals - Under 18,Sheltered TH Homeless Individuals - Age 18 to 24,Sheltered TH Homeless Individuals - Over 24,Sheltered TH Homeless Individuals - Female,Sheltered TH Homeless Individuals - Male,Sheltered TH Homeless Individuals - Transgender,Sheltered TH Homeless Individuals - Non-Hispanic/Non-Latino,Sheltered TH Homeless Individuals - Hispanic/Latino,Sheltered TH Homeless Individuals - White,Sheltered TH Homeless Individuals - Black or African American,Sheltered TH Homeless Individuals - Asian,Sheltered TH Homeless Individuals - American Indian or Alaska Native,Sheltered TH Homeless Individuals - Native Hawaiian or Other Pacific Islander,Sheltered TH Homeless Individuals - Multiple Races,Sheltered SH Homeless Individuals,Sheltered SH Homeless Individuals - Age 18 to 24,Sheltered SH Homeless Individuals - Over 24,Sheltered SH Homeless Individuals - Female,Sheltered SH Homeless Individuals - Male,Sheltered SH Homeless Individuals - Transgender,Sheltered SH Homeless Individuals - Non-Hispanic/Non-Latino,Sheltered SH Homeless Individuals - Hispanic/Latino,Sheltered SH Homeless Individuals - White,Sheltered SH Homeless Individuals - Black or African American,Sheltered SH Homeless Individuals - Asian,Sheltered SH Homeless Individuals - American Indian or Alaska Native,Sheltered SH Homeless Individuals - Native Hawaiian or Other Pacific Islander,Sheltered SH Homeless Individuals - Multiple Races,Sheltered Total Homeless Individuals,Sheltered Total Homeless Individuals - Under 18,Sheltered Total Homeless Individuals - Age 18 to 24,Sheltered Total Homeless Individuals - Over 24,Sheltered Total Homeless Individuals - Female,Sheltered Total Homeless Individuals - Male,Sheltered Total Homeless Individuals - Transgender,Sheltered Total Homeless Individuals - Non-Hispanic/Non-Latino,Sheltered Total Homeless Individuals - Hispanic/Latino,Sheltered Total Homeless Individuals - White,Sheltered Total Homeless Individuals - Black or African American,Sheltered Total Homeless Individuals - Asian,Sheltered Total Homeless Individuals - American Indian or Alaska Native,Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander,Sheltered Total Homeless Individuals - Multiple Races,Unsheltered Homeless Individuals,Unsheltered Homeless Individuals - Under 18,Unsheltered Homeless Individuals - Age 18 to 24,Unsheltered Homeless Individuals - Over 24,Unsheltered Homeless Individuals - Female,Unsheltered Homeless Individuals - Male,Unsheltered Homeless Individuals - Transgender,Unsheltered Homeless Individuals - Non-Hispanic/Non-Latino,Unsheltered Homeless Individuals - Hispanic/Latino,Unsheltered Homeless Individuals - White,Unsheltered Homeless Individuals - Black or African American,Unsheltered Homeless Individuals - Asian,Unsheltered Homeless Individuals - American Indian or Alaska Native,Unsheltered Homeless Individuals - Native Hawaiian or Other Pacific Islander,Unsheltered Homeless Individuals - Multiple Races,Overall Homeless People in Families,Overall Homeless People in Families - Under 18,Overall Homeless People in Families - Age 18 to 24,Overall Homeless People in Families - Over 24,Overall Homeless People in Families - Female,Overall Homeless People in Families - Male,Overall Homeless People in Families - Transgender,Overall Homeless People in Families - Non-Hispanic/Non-Latino,Overall Homeless People in Families - Hispanic/Latino,Overall Homeless People in Families - White,Overall Homeless People in Families - Black or African American,Overall Homeless People in Families - Asian,Overall Homeless People in Families - American Indian or Alaska Native,Overall Homeless People in Families - Native Hawaiian or Other Pacific Islander,Overall Homeless People in Families - Multiple Races,Sheltered ES Homeless People in Families,Sheltered ES Homeless People in Families - Under 18,Sheltered ES Homeless People in Families - Age 18 to 24,Sheltered ES Homeless People in Families - Over 24,Sheltered ES Homeless People in Families - Female,Sheltered ES Homeless People in Families - Male,Sheltered ES Homeless People in Families - Transgender,Sheltered ES Homeless People in Families - Non-Hispanic/Non-Latino,Sheltered ES Homeless People in Families - Hispanic/Latino,Sheltered ES Homeless People in Families - White,Sheltered ES Homeless People in Families - Black or African American,Sheltered ES Homeless People in Families - Asian,Sheltered ES Homeless People in Families - American Indian or Alaska Native,Sheltered ES Homeless People in Families - Native Hawaiian or Other Pacific Islander,Sheltered ES Homeless People in Families - Multiple Races,Sheltered TH Homeless People in Families,Sheltered TH Homeless People in Families - Under 18,Sheltered TH Homeless People in Families - Age 18 to 24,Sheltered TH Homeless People in Families - Over 24,Sheltered TH Homeless People in Families - Female,Sheltered TH Homeless People in Families - Male,Sheltered TH Homeless People in Families - Transgender,Sheltered TH Homeless People in Families - Non-Hispanic/Non-Latino,Sheltered TH Homeless People in Families - Hispanic/Latino,Sheltered TH Homeless People in Families - White,Sheltered TH Homeless People in Families - Black or African American,Sheltered TH Homeless People in Families - Asian,Sheltered TH Homeless People in Families - American Indian or Alaska Native,Sheltered TH Homeless People in Families - Native Hawaiian or Other Pacific Islander,Sheltered TH Homeless People in Families - Multiple Races,Sheltered Total Homeless People in Families,Sheltered Total Homeless People in Families - Under 18,Sheltered Total Homeless People in Families - Age 18 to 24,Sheltered Total Homeless People in Families - Over 24,Sheltered Total Homeless People in Families - Female,Sheltered Total Homeless People in Families - Male,Sheltered Total Homeless People in Families - Transgender,Sheltered Total Homeless People in Families - Non-Hispanic/Non-Latino,Sheltered Total Homeless People in Families - Hispanic/Latino,Sheltered Total Homeless People in Families - White,Sheltered Total Homeless People in Families - Black or African American,Sheltered Total Homeless People in Families - Asian,Sheltered Total Homeless People in Families - American Indian or Alaska Native,Sheltered Total Homeless People in Families - Native Hawaiian or Other Pacific Islander,Sheltered Total Homeless People in Families - Multiple Races,Unsheltered Homeless People in Families,Unsheltered Homeless People in Families - Under 18,Unsheltered Homeless People in Families - Age 18 to 24,Unsheltered Homeless People in Families - Over 24,Unsheltered Homeless People in Families - Female,Unsheltered Homeless People in Families - Male,Unsheltered Homeless People in Families - Transgender,Unsheltered Homeless People in Families - Non-Hispanic/Non-Latino,Unsheltered Homeless People in Families - Hispanic/Latino,Unsheltered Homeless People in Families - White,Unsheltered Homeless People in Families - Black or African American,Unsheltered Homeless People in Families - Asian,Unsheltered Homeless People in Families - American Indian or Alaska Native,Unsheltered Homeless People in Families - Native Hawaiian or Other Pacific Islander,Unsheltered Homeless People in Families - Multiple Races,Overall Homeless Family Households,Sheltered ES Homeless Family Households,Sheltered TH Homeless Family Households,Sheltered Total Homeless Family Households,Unsheltered Homeless Family Households,Overall Chronically Homeless,Sheltered ES Chronically Homeless,Sheltered SH Chronically Homeless,Sheltered Total Chronically Homeless,Unsheltered Chronically Homeless,Overall Chronically Homeless Individuals,Sheltered ES Chronically Homeless Individuals,Sheltered SH Chronically Homeless Individuals,Sheltered Total Chronically Homeless Individuals,Unsheltered Chronically Homeless Individuals,Overall Chronically Homeless People in Families,Sheltered ES Chronically Homeless People in Families,Sheltered Total Chronically Homeless People in Families,Unsheltered Chronically Homeless People in Families,Overall Homeless Veterans,Overall Homeless Veterans - Female,Overall Homeless Veterans - Male,Overall Homeless Veterans - Transgender,Overall Homeless Veterans - Non-Hispanic/Non-Latino,Overall Homeless Veterans - Hispanic/Latino,Overall Homeless Veterans - White,Overall Homeless Veterans - Black or African American,Overall Homeless Veterans - Asian,Overall Homeless Veterans - American Indian or Alaska Native,Overall Homeless Veterans - Native Hawaiian or Other Pacific Islander,Overall Homeless Veterans - Multiple Races,Sheltered ES Homeless Veterans,Sheltered ES Homeless Veterans - Female,Sheltered ES Homeless Veterans - Male,Sheltered ES Homeless Veterans - Transgender,Sheltered ES Homeless Veterans - Non-Hispanic/Non-Latino,Sheltered ES Homeless Veterans - Hispanic/Latino,Sheltered ES Homeless Veterans - White,Sheltered ES Homeless Veterans - Black or African American,Sheltered ES Homeless Veterans - Asian,Sheltered ES Homeless Veterans - American Indian or Alaska Native,Sheltered ES Homeless Veterans - Native Hawaiian or Other Pacific Islander,Sheltered ES Homeless Veterans - Multiple Races,Sheltered TH Homeless Veterans,Sheltered TH Homeless Veterans - Female,Sheltered TH Homeless Veterans - Male,Sheltered TH Homeless Veterans - Transgender,Sheltered TH Homeless Veterans - Non-Hispanic/Non-Latino,Sheltered TH Homeless Veterans - Hispanic/Latino,Sheltered TH Homeless Veterans - White,Sheltered TH Homeless Veterans - Black or African American,Sheltered TH Homeless Veterans - Asian,Sheltered TH Homeless Veterans - American Indian or Alaska Native,Sheltered TH Homeless Veterans - Native Hawaiian or Other Pacific Islander,Sheltered TH Homeless Veterans - Multiple Races,Sheltered SH Homeless Veterans,Sheltered SH Homeless Veterans - Female,Sheltered SH Homeless Veterans - Male,Sheltered SH Homeless Veterans - Transgender,Sheltered SH Homeless Veterans - Non-Hispanic/Non-Latino,Sheltered SH Homeless Veterans - Hispanic/Latino,Sheltered SH Homeless Veterans - White,Sheltered SH Homeless Veterans - Black or African American,Sheltered SH Homeless Veterans - Asian,Sheltered SH Homeless Veterans - American Indian or Alaska Native,Sheltered SH Homeless Veterans - Native Hawaiian or Other Pacific Islander,Sheltered SH Homeless Veterans - Multiple Races,Sheltered Total Homeless Veterans,Sheltered Total Homeless Veterans - Female,Sheltered Total Homeless Veterans - Male,Sheltered Total Homeless Veterans - Transgender,Sheltered Total Homeless Veterans - Non-Hispanic/Non-Latino,Sheltered Total Homeless Veterans - Hispanic/Latino,Sheltered Total Homeless Veterans - White,Sheltered Total Homeless Veterans - Black or African American,Sheltered Total Homeless Veterans - Asian,Sheltered Total Homeless Veterans - American Indian or Alaska Native,Sheltered Total Homeless Veterans - Native Hawaiian or Other Pacific Islander,Sheltered Total Homeless Veterans - Multiple Races,Unsheltered Homeless Veterans,Unsheltered Homeless Veterans - Female,Unsheltered Homeless Veterans - Male,Unsheltered Homeless Veterans - Transgender,Unsheltered Homeless Veterans - Non-Hispanic/Non-Latino,Unsheltered Homeless Veterans - Hispanic/Latino,Unsheltered Homeless Veterans - White,Unsheltered Homeless Veterans - Black or African American,Unsheltered Homeless Veterans - Asian,Unsheltered Homeless Veterans - American Indian or Alaska Native,Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander,Unsheltered Homeless Veterans - Multiple Races

import matplotlib.pyplot as plt
import seaborn as sns

# Distribution of Overall Homeless Individuals by Year
sns.histplot(data=merged_df, x='Year', hue='Overall Homeless Individuals', multiple='stack')
plt.title('Distribution of Overall Homeless Individuals by Year')
plt.show()

sns.histplot(data=merged_df, x='Year', hue='Categorical_Variable', multiple='stack', palette='Set1')
plt.title('Distribution of Overall Homeless Individuals by Year')
plt.show()

sns.histplot(data=merged_df, x='Year')